# Generated by Django 4.1.1 on 2022-09-26 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='csvS')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=120)),
                ('emp_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='emp_shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_time', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='emp_statustype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='emp_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True)),
                ('emp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsdashboard.emp')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmsdashboard.emp_statustype')),
            ],
        ),
        migrations.AddField(
            model_name='emp',
            name='emp_shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsdashboard.emp_shift'),
        ),
    ]
