# Generated by Django 4.1.1 on 2022-09-29 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsdashboard', '0002_record_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record_delete',
            old_name='Date',
            new_name='date',
        ),
    ]
