# Generated by Django 4.1.1 on 2022-09-29 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmsdashboard', '0004_alter_record_delete_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record_delete',
            old_name='date',
            new_name='day',
        ),
        migrations.AddField(
            model_name='record_delete',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record_delete',
            name='deactivated',
            field=models.BooleanField(default=False),
        ),
    ]
