# Generated by Django 4.1.1 on 2022-09-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsdashboard', '0005_rename_date_record_delete_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record_delete',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
