# Generated by Django 4.1.1 on 2022-09-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsdashboard', '0006_record_delete_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='record_created',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
